<?php 
include_once("includes/header.php");
include("includes/_breadcrumbs.php");
include("includes/_hero.php");
include("includes/_artists-cards.php");
include("includes/_genres.php");
include("includes/_why-chose-leg.php");
include("includes/_blogs.php");
include("includes/_faqs.php");
include("includes/_find-local.php");
?>
<?php
include_once("includes/footer.php");
?>